### ISSUE TITLE
PA Review: User Auth

### ISSUE THREAD

**Issue by hanhee-song** [hanhee-song/slic#2]

**Comment by AM-Harris** [comment]
Functionally:
- This looks really great! Nice work!
- Guest log in button should actually log them in, not just fill in the fields.

Styling

 - needs a little more love :) :
- In general, try to match the styling of slack exactly. The goal is to make this an exact clone, and a way to show that you would be able work with a designer's exact specifications. 
- Remove sign out button when not logged in
- Need splash image for welcome page
- Real slack doesn't have sign up or login buttons on the header, but has a get started button (with no email input) and a 'already a member, sign in' option below it
- The log in form and sign up form do not look like those of the real slack. They work very well, but need to match slack's styling.
- Remove sign in and log in buttons once successfully logged in.

**Comment by AM-Harris** [comment]
Looks good to me!
